### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by nbielak** [nbielak/eventbriteclone#2]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, action, reducers
- [ ] Presentational Components 
- [ ] Styling
- [ ] Smooth Bug-free Navigation
- [ ] Adequate and Appropriate Seeds

**Comment by andywynkoop** [comment]
Hey Nick, 
Here are a few changes to make for the user auth MVP:
- [x] Remove redux logger and all console logs from production
- [x] Clicking sign in button with no email should give me an error of some kind
- [x] All buttons in nav bar should have `'cursor: pointer` on hover
- [x] Going to a random route like `/fsddsbrbr` should show a 404 page or redirect back to `/`
- [x] Trying to log in with the wrong password should show an error message
- [x] Once redirected to the sign up or log in screen, I shouldn't be allowed to manually navigate to the other (or at least should see an error message when I try to create a duplicate account)
Overall, this looks great so far!
